### ISSUE TITLE
There is an error

### ISSUE THREAD

**Issue by Mirageclaw** [GoSecure/dtd-finder#3]
hi 
Encountered a problem: run `java -jar dtd-finder-1.1-SNAPSHOT-all.jar fuzztest/fmw_14.1.1.0.0_wls_lite_quick_generic.jar `
The error is as follows:
```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true                                                                                                                                    
Exception in thread "main" java.io.IOException: Error detected parsing the header                                                                                                                                
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:316)                                                                                       
        at DtdFinder.scanTarFile(DtdFinder.kt:110)                                                                                                                                                               
        at DtdFinderKt.main(DtdFinder.kt:169)                                                                                                                                                                    
Caused by: java.lang.IllegalArgumentException: Invalid byte 77 at offset 0 in 'MANIFEST' len=8                                                                                                                   
        at org.apache.commons.compress.archivers.tar.TarUtils.parseOctal(TarUtils.java:141)                                                                                                                      
        at org.apache.commons.compress.archivers.tar.TarUtils.parseOctalOrBinary(TarUtils.java:171)                                                                                                              
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseOctalOrBinary(TarArchiveEntry.java:1385)                                                                                               
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1301)                                                                                                   
        at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:428)                                                                                                            
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:314)                                                                                       
        ... 2 more     
```
how to set up

**Comment by h3xstream** [comment]
It is expecting a tar file or a directory. 

Two options:
 - You can point to the folder where the jar is present
 - You can extract the `.jar` and scan the extracted content.

To support `.jar` or `.zip` file directly, additional code would be needed here.
https://github.com/GoSecure/dtd-finder/blob/6b9f1ce7760d4211074a3da2b9f7773aaffa0203/src/main/kotlin/DtdFinder.kt#L167-L171

**Comment by h3xstream** [comment]
Found some time to implement the feature:

Here is the behavior.
```
>java -jar dtd-finder-1.1-SNAPSHOT-all.jar erlang.zip
Scanning ZIP file C:\Code\dtd-finder\target\erlang.zip

 [=] Found a DTD: /erlang.zip!/erlang/application.dtd
 [??] java.io.FileNotFoundException : C:\Users\philippe\AppData\Local\Temp\common.dtd (The system cannot find the file specified)
Testing 1 entities : [common]
 [+] The entity common is injectable

 [=] Found a DTD: /erlang.zip!/erlang/common.dtd
 [??] java.io.FileNotFoundException : C:\Users\philippe\AppData\Local\Temp\common.entities.dtd (The system cannot find the file specified)
Testing 3 entities : [common.entities, block, inline]
 [+] The entity common.entities is injectable

 [=] Found a DTD: /erlang.zip!/erlang/common.entities.dtd
 [??] java.io.FileNotFoundException : C:\Users\philippe\AppData\Local\Temp\xhtml-lat1.ent (The system cannot find the file specified)
Testing 4 entities : [ISOlat1, amp, gt, lt]
 [+] The entity ISOlat1 is injectable

 [=] Found a DTD: /erlang.zip!/erlang/common.header.dtd
Testing 0 entities : []

 [=] Found a DTD: /erlang.zip!/erlang/xhtml1-strict.dtd
 [??] java.io.FileNotFoundException : C:\Users\philippe\AppData\Local\Temp\xhtml-lat1.ent (The system cannot find the file specified)
Testing 54 entities : [HTMLlat1, HTMLsymbol, HTMLspecial, ContentType, ContentTypes, Charset, Charsets, LanguageCode, Character, Number, LinkTypes, MediaDesc, URI, UriList, Datetime, Script, StyleSheet, Text, Length, MultiLength, Pixels, Shape, Coords, coreattrs, i18n, events, focus, attrs, special.pre, special, fontstyle, phrase, inline.forms, misc.inline, misc, inline, Inline, heading, lists, blocktext, block, Block, Flow, a.content, pre.content, form.content, button.content, head.misc, InputType, TFrame, TRules, cellhalign, cellvalign, Scope]
 [+] The entity HTMLlat1 is injectable

Report written to erlang.zip-dtd-report.md
```
